export const shipTemplate = {
	id: 0,
	name: 'Rowboat',
	legend: 'Nothing Lol',
	durability: 350,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 30,
	stability: 10,
	turning: 100,
	mainType: 'Boat',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	hullArmorSlot: 1,
	quarterMasterSlot: 0,
	cannonSlot: 0,
	siegeWeaponSlot: 0,
	sailMaterialSlot: 0,
	shipCrewSlot: 0,
	ramSlot: 0,
	deckhandSlot: 1
};

export const hullTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	mainType: 'Hull Armor',
	subType: 'None',
	rarity: 'Common',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/hull armor/0.jpg'
};

export const hullEcnhantTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	mainType: 'Hull Enchant',
	subType: 'None',
	rarity: 'Common',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/hull enchant/0.jpg'
};

export const sailTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	mainType: 'Sail Material',
	subType: 'None',
	rarity: 'Common',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/sail material/0.jpg'
};

export const sailMaterialEnchantTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'Sail Material Enchant',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/sail material enchant/0.jpg'
};

export const cannonsTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	mainType: 'Cannon',
	subType: 'None',
	rarity: 'Common',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/cannon/0.jpg'
};

export const deckhandTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	mainType: 'Deckhand',
	subType: 'None',
	rarity: 'Common',
	rarityColor: '#7D7D7F',
	imageId: 'assets/images/deckhand/0.jpg'
};

export const quartermasterTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	mainType: 'Quartermaster',
	subType: 'None',
	rarity: 'Common',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/quartermaster/0.jpg'
};

export const siegeWeaponTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	mainType: 'Siege Weapon',
	subType: 'None',
	rarity: 'Common',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/siege weapon/0.jpg'
};

export const ramTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	mainType: 'Ram',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/ram/0.jpg'
};

export const ramEnchantTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'Ram Enchant',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/ram enchant/0.jpg'
};

export const shipCrewTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	durability: 0,
	magicStorage: 0,
	ramDefense: 0,
	ramStrength: 0,
	resilience: 0,
	speed: 0,
	stability: 0,
	turning: 0,
	maxLevel: 0,
	mainType: 'Ship Crew',
	subType: 'None',
	rarity: 'Common',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/ship crew/0.jpg'
};
