export const statTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/unknown.png'
};

export const accessoryTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#7D7D7F',
	imageId: 'assets/images/accessory/0.jpg'
};

export const chestplateTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/chestplate/0.jpg'
};

export const pantsTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/pants/0.jpg'
};

export const gemTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/gem/0.jpg'
};

export const enchantTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/enchant/0.jpg'
};
export const modifierTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'assets/images/modifier/0.jpg'
};
