export const statTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'https://i.imgur.com/iwUANFD.jpg'
};

export const accessoryTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#7D7D7F',
	imageId: 'https://i.imgur.com/ynJYNoA.jpg'
};

export const chestplateTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'https://i.imgur.com/Uj7r6Fm.jpg'
};

export const pantsTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'https://i.imgur.com/U9Z0chG.jpg'
};

export const gemTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'https://i.imgur.com/5pGLWmQ.jpg'
};

export const enchantTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'https://i.imgur.com/PzIWvMv.jpg'
};
export const modifierTemplate = {
	id: 0,
	name: 'None',
	legend: 'Nothing Lol',
	defense: 0,
	power: 0,
	agility: 0,
	attackSize: 0,
	attackSpeed: 0,
	intensity: 0,
	insanity: 0,
	drawback: 0,
	warding: 0,
	maxLevel: 0,
	gemNo: 0,
	mainType: 'None',
	subType: 'None',
	rarity: 'None',
	rarityColor: '#FFFFFF',
	imageId: 'https://i.imgur.com/iKfI8Cp.jpg'
};
